name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --reporter=dot,html

      - name: Create a sample HTML file
        run: |
          mkdir -p dist
          echo "<html><body><h1>Hello, Pages!</h1></body></html>" > tests/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Playwright Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: playwright-report
          retention-days: 7

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        
      - name: List Playwright Report Files
        run: |
          echo "Listing Playwright report files:"
          ls -R playwright-report || echo "No report files found."
