name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies for Playwright
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              libwoff1 \
              libvpx7 \
              libevent-2.1-7 \
              libopus0 \
              libgstreamer1.0-0 \
              libgstreamer-plugins-base1.0-0 \
              libgstreamer-gl1.0-0 \
              libgstreamer-plugins-good1.0-0 \
              libgstreamer-plugins-bad1.0-0 \
              libflite1 \
              libharfbuzz-icu0 \
              libhyphen0 \
              libgles2-mesa \
              libavif13 \
              libx264-155 \
      - name: Install Playwright
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      
      - name: Run tests
        run: npx playwright test --reporter=dot,html
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: test-results/html-report
