name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: test-results

  setup-pages:
    runs-on: ubuntu-latest
    needs: test  # Ensures 'test' job is completed before this job runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project for GitHub Pages
        run: |
          npm install
          npm run build  # Replace with your build command for GitHub Pages
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with the folder containing the built project

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: test  # Ensures 'test' job is completed before this job runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: test-results  # Replace with your actual test results directory
